stages:
 - build
 - test

variables:
 IMAGE: node:20-alpine

cache:
 key:
  files:
   - package-lock.json
 paths:
  - .npm/

#################
## BUILD STAGE ##
#################

Build:
 stage: build
 script:
  - npm ci --cache .npm --prefer-offline
 artifacts:
  name: "node-dependencies-$CI_COMMIT_SHORT_SHA"
  paths: 
   - node_modules/
  expire_in: 1 hour


#################
## TEST STAGE ###
#################

Lint:
 stage: test
 image: $IMAGE

 cache:
 key:
  files:
   - package-lock.json
 paths:
  - .npm/
 
 script:
  - npm ci --cache .npm --prefer-offline
  - npm run lint


